PROGRAM:=btdc
OBJS:=misc.o

CFLAGS:=-g -O3 -Wextra -Wall -Werror -std=gnu11
LDLIBS:=

all: $(PROGRAM)

$(PROGRAM): $(PROGRAM).o $(OBJS)
	$(CC) $< $(OBJS) $(LDLIBS) -o $@

clean:
	$(RM) -v $(PROGRAM) $(PROGRAM).o $(OBJS)
